server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Routing SPA : les chemins inconnus retombent sur index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    location /healthz { return 200 'ok'; add_header Content-Type text/plain; }

    gzip on;
    gzip_types text/css application/javascript application/json image/svg+xml;
}
